"""
Backtesting strategy dispatcher.

This module is intentionally thin. It:
  1. Defines the Signal dataclass (shared by all strategies)
  2. Looks up the correct strategy from the registry for the active asset
  3. Delegates signal generation to that strategy's generate_signals()

All strategy logic lives in strategies/{asset}.py, not here.
To add a new asset, create strategies/{asset}.py and register it in strategies/__init__.py.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd

from strategies import get_strategy


@dataclass
class Signal:
    """A single trading signal generated by a strategy at a specific bar."""

    bar_index: int
    timestamp: pd.Timestamp
    action: str              # "LONG" | "SHORT"
    entry_price: float
    stop_loss: float
    target_price: float
    confidence: float
    risk_reward: float
    confluence_factors: list[str]
    entry_type: str = "limit"   # "limit" (price must revisit level) | "market" (next bar open)


def generate_signals(
    df_1h: pd.DataFrame,
    df_daily: pd.DataFrame,
    asset: str | None = None,
    min_confidence: float | None = None,
    min_rr: float | None = None,
    ema_periods: list[int] | None = None,
    rsi_period: int = 14,
    macd_fast: int = 12,
    macd_slow: int = 26,
    macd_signal_period: int = 9,
    atr_period: int = 14,
    df_15m: pd.DataFrame | None = None,
) -> list[Signal]:
    """
    Dispatch signal generation to the registered strategy for the active asset.

    Args:
        df_1h:              1H OHLCV DataFrame
        df_daily:           Daily OHLCV for trend context
        asset:              Asset symbol — if None, reads from cfg
        min_confidence:     Override strategy default (optional)
        min_rr:             Override strategy default (optional)
        ema_periods:        EMA periods (falls back to strategy default [20,50,200])
        rsi_period:         RSI period
        macd_fast/slow/signal_period: MACD params
        atr_period:         ATR period

    Returns:
        List of Signal objects
    """
    from core.config import cfg

    symbol = (asset or cfg.asset.symbol).upper()
    entry = get_strategy(symbol)
    strategy = entry.config

    # Allow callers to override thresholds (e.g. from CLI args or config)
    if min_confidence is not None:
        strategy = _with_overrides(strategy, min_confidence=min_confidence)
    if min_rr is not None:
        strategy = _with_overrides(strategy, min_rr=min_rr)

    if ema_periods is None:
        ema_periods = [20, 50, 200]

    kwargs = dict(
        df_1h=df_1h,
        df_daily=df_daily,
        strategy=strategy,
        ema_periods=ema_periods,
        rsi_period=rsi_period,
        macd_fast=macd_fast,
        macd_slow=macd_slow,
        macd_signal_period=macd_signal_period,
        atr_period=atr_period,
    )
    if df_15m is not None:
        kwargs["df_15m"] = df_15m
    return entry.generate_signals(**kwargs)


def _with_overrides(strategy, **kwargs):
    """Return a copy of a StrategyConfig with specific fields overridden."""
    import dataclasses
    return dataclasses.replace(strategy, **kwargs)
